apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbproxy0-deployment
  labels:
    app: dbproxy0
spec: 
  serviceName: dbproxy0-service
  replicas: 1
  selector:
    matchLabels:
      app: dbproxy0
  template:
    metadata:
      labels:
        app: dbproxy0
    spec: 
      containers:
        - name: dbproxy0
          image: systems:latest
          command: ["./dbproxy_start.sh"]
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 800m
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
          - containerPort: 38875
          lifecycle:
            preStop:
              exec:
                command:
                  - ./preStop.sh
      terminationGracePeriodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dbproxy0-service
spec:
  clusterIP: None
  selector:
    app: dbproxy0
  ports:
    - protocol: TCP
      port: 38875
      targetPort: 38875
