apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec: 
  serviceName: scheduler-service
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec: 
      containers:
        - name: scheduler
          image: systems:latest
          command: ["./systems_start.sh"]
          imagePullPolicy: Never
          volumeMounts:
          - mountPath: /perf
            name: scheduler-mount
      volumes:
      - name: scheduler-mount
        hostPath:
          # Note: use k8s_start.sh to deploy this yaml file
          path: {{path}}/perf
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 2077
      targetPort: 2077
      nodePort: 32077
  selector:
    app: scheduler